# Generated by Django 5.2 on 2025-04-10 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.DeleteModel(
            name='CarCategory',
        ),
    ]
