# Generated by Django 5.2 on 2025-04-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_car_category_delete_carcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='agency',
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
